Гарантии безопасности исключений (exception safety guarantees) описывают, как код будет реагировать в случае возникновения исключений, особенно с точки зрения управления ресурсами и состояния программы. Эти гарантии очень важны для создания надёжных и стабильных приложений. Принято выделять три основных уровня гарантий безопасности исключений:

**1. No-throw guarantee (Гарантия отсутствия исключений)**

Функция с такой гарантией обещает, что никакие исключения не будут брошены в процессе её выполнения. Это означает, что функция либо не генерирует исключения вообще, либо обрабатывает все возможные исключения самостоятельно внутри себя. Очень важно для функций, которые управляют критичными ресурсами, например, для деструкторов, которые должны быть no-throw, чтобы избежать возможности возникновения исключений во время разрушения объектов.
Такие функции должны быть [[noexcept]] (по нормам хорошего тона)

**2. Strong guarantee (Строгая гарантия)**

Обещает, что в случае возникновения исключения состояние программы останется неизменным. Это означает, что любые изменения, внесённые функцией, будут полностью отменены, если что-то пойдет не так. Такие гарантии часто реализуются с помощью техники "commit or rollback", где изменения применяются только после того, как все потенциально опасные операции выполнены успешно. Это типично для операций, требующих атомарности.

Пример:

```cpp
std::vector<int> data;

void addToData(int value) {
    std::vector<int> temp = data;  // Копируем данные
    temp.push_back(value);         // Модифицируем копию
    data = temp;                   // Атомарно заменяем старые данные на новые, если здесь произойдет исключение, data останется неизменной
}
```

**3. Basic guarantee (Базовая гарантия)**

Утверждает, что в случае возникновения исключений все ресурсы по-прежнему будут управляемы (т.е. нет утечек памяти), и объекты останутся в валидном (но не обязательно предсказуемом) состоянии. Функция обеспечит безопасное продолжение выполнения программы, но конкретное состояние объектов может быть неопределённым.

Пример:
```cpp 
class DataWrapper 
{ 
public:     
	std::vector<int> data;     
	void addData(int value) 
	{         
	data.push_back(value);  // Если push_back бросит исключение 
	//(например, std::bad_alloc), объект data останется в валидном состоянии     
	} 
}; 
```

